### ISSUE TITLE
靠这个make bot到底什么意思？

### ISSUE THREAD

**Issue by bhj8** [wechaty/python-wechaty-template#8]
.sh运行成功，微信扫码登录后。
在哪make bot？

是指运行bot.py吗？运行了报错wechaty_puppet.exceptions.WechatyPuppetConfigurationError: WechatyPuppetConfigurationError("can't not ping endpoint: 60.188.217.15:8080", None, None)
是指在.sh运行后的窗口里输入make bot吗？没用啊。。

这make bot到底怎么搞

**Comment by bhj8** [comment]
搞定了，这里有N多坑。

这个make bot，就是指运行bot.py文件。报错是因为，默认连接到它的什么鬼服务器，连不上。应该连自己刚docker出来的本地端口。在bot.py中加入以下代码即可

os.environ['WECHATY_PUPPET_SERVICE_ENDPOINT'] = '127.0.0.1:8080'

**Comment by AC-Unicorn** [comment]
补充一点, 运行bot.py之前. 除了`WECHATY_PUPPET_SERVICE_ENDPOINT` 这个环境变量，还要再设置一个环境变量来存padlocal的token. （这文档是真够敷衍的
:
```
export TOKEN=1fe5f846-3cfb-401d-b20c-XXXXX
```

**Comment by bhj8** [comment]
建议大家也别搞什么个人微信机器人了，浪费自己时间。微信官方都是静止了， 我搞成了几天就被ban了。直接接个公众号都比这方便

**Comment by zzchust** [comment]
> 建议大家也别搞什么个人微信机器人了，浪费自己时间。微信官方都是静止了， 我搞成了几天就被ban了。直接接个公众号都比这方便

hhhhh   刚刚封了一个号由来看这个教程的.. 请问个人公众号用的啥代码库，求一个

**Comment by bhj8** [comment]
> > 建议大家也别搞什么个人微信机器人了，浪费自己时间。微信官方都是静止了， 我搞成了几天就被ban了。直接接个公众号都比这方便
> 
> hhhhh 刚刚封了一个号由来看这个教程的.. 请问个人公众号用的啥代码库，求一个

我注册了一个微信公众号，也就300手续费。亲戚朋友随便搞张营业执照就好了，个体经商户的就行。库我用werobot，贼方便。
